# Generated by Django 3.1.1 on 2020-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_money_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='money_owned',
        ),
        migrations.AddField(
            model_name='user',
            name='money_owned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
