# Generated by Django 3.1.1 on 2020-10-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainsite.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0004_auto_20201002_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(default=mainsite.models.f, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
